version: '3.7'

services:
  vchat-backend:
    container_name: ${PROJECT_NAME}-backend
    build:
      context: .
      target: ${NODE_ENV}
    links:
      - "vchat-db:database"
      - "vchat-redis:redis"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run ${START_COMMAND}
    env_file:
      - .env
    depends_on:
      - vchat-db
      - vchat-redis
    tty: true

  vchat-db:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  vchat-redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:5
    expose:
      - 6379
